controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
  - name: fake_right_hand_controller
    joints:
      - right_gripper_l_finger_joint